easy_admin:
  design:
    brand_color: red
    menu:
      - label: 'Produit'
        icon: 'newspaper -o'
        children:
          - {entity: 'Produit'}
      - label: 'Imperfection'
        icon: 'newspaper -o'
        children:
          - {entity: 'Imperfection'}
      - label: 'Peau'
        icon: 'newspaper -o'
        children:
          - {entity: 'Typedepeau', label: 'Type de peau'}
  entities:
    Produit:
      class: App\Entity\Product

    Imperfection:
      class: App\Entity\ImperfectionType
    Typedepeau:
      class:  App\Entity\SkinType
